In [2]:
import pandas as pd

billboard = pd.read_csv('billboard.csv')
billboard

,year,artist,track,time,date.entered,wk1,wk2,wk3,wk4,wk5,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,87,82.0,72.0,77.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,91,87.0,92.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,81,70.0,68.0,67.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,3 Doors Down,Loser,4:24,2000-10-21,76,76.0,72.0,69.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,57,34.0,25.0,17.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,86,83.0,77.0,74.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,85,83.0,83.0,82.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,95,94.0,91.0,85.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,matchbox twenty,Bent,4:12,2000-04-29,60,37.0,29.0,24.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
billboard2 = pd.melt(billboard, 
                     id_vars = ['year', 'artist', 'track', 'time', 'date.entered'],
                     var_name = 'week',
                     value_name = 'rating')
billboard2

,year,artist,track,time,date.entered,week,rating
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...
24087,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,wk76,NaN
24088,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,wk76,NaN
24089,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,wk76,NaN
24090,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk76,NaN
24091,2000,matchbox twenty,Bent,4:12,2000-04-29,wk76,NaN

In [6]:
billboard3 = billboard2[['year', 'artist', 'track', 'time']]
billboard3

       year            artist                    track  time
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22
1      2000           2Ge+her  The Hardest Part Of ...  3:15
2      2000      3 Doors Down               Kryptonite  3:53
3      2000      3 Doors Down                    Loser  4:24
4      2000          504 Boyz            Wobble Wobble  3:35
...     ...               ...                      ...   ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10
24088  2000  Yearwood, Trisha          Real Live Woman  3:55
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19
24090  2000     Zombie Nation            Kernkraft 400  3:30
24091  2000   matchbox twenty                     Bent  4:12

[24092 rows x 4 columns]

In [7]:
billboard3[billboard3['track'] == 'Loser']

       year        artist  track  time
3      2000  3 Doors Down  Loser  4:24
320    2000  3 Doors Down  Loser  4:24
637    2000  3 Doors Down  Loser  4:24
954    2000  3 Doors Down  Loser  4:24
1271   2000  3 Doors Down  Loser  4:24
...     ...           ...    ...   ...
22510  2000  3 Doors Down  Loser  4:24
22827  2000  3 Doors Down  Loser  4:24
23144  2000  3 Doors Down  Loser  4:24
23461  2000  3 Doors Down  Loser  4:24
23778  2000  3 Doors Down  Loser  4:24

[76 rows x 4 columns]

In [8]:
billboard3.drop_duplicates()    # 고유한 행 하나를 남기고 나머지 행을 모두 삭제
                                # Series, DataFrame, Index 객체에 적용 가능

     year            artist                    track  time
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22
1    2000           2Ge+her  The Hardest Part Of ...  3:15
2    2000      3 Doors Down               Kryptonite  3:53
3    2000      3 Doors Down                    Loser  4:24
4    2000          504 Boyz            Wobble Wobble  3:35
..    ...               ...                      ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10
313  2000  Yearwood, Trisha          Real Live Woman  3:55
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19
315  2000     Zombie Nation            Kernkraft 400  3:30
316  2000   matchbox twenty                     Bent  4:12

[317 rows x 4 columns]

In [9]:
billboard4 = billboard3.drop_duplicates()
billboard4[billboard4['track'] == 'Loser']

   year        artist  track  time
3  2000  3 Doors Down  Loser  4:24

In [12]:
billboard['wk1'].drop_duplicates()

0      87
1      91
2      81
3      76
4      57
       ..
238    52
239    65
252    15
272    61
316    60
Name: wk1, Length: 63, dtype: int64